version: "3"

services:
  front:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    container_name: react-front-container
    ports:
      - "5173:5173"  # Frontend exposed port
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - ./frontend/.env
    networks:
      - mern-network
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3002:3002"  # Backend port exposed

    env_file:
      - ./backend/.env
    networks:
      - mern-network
    volumes:
      - ./backend:/src
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongoData:/data/db
    networks:
      - mern-network

networks:
  mern-network:

volumes:
  mongoData:
